language: php

php:
  - 5.3
  - 5.4

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

notifications:
  email:
    recipients:
      - dev@itembase.biz
    on_success: always
    on_failure: always