parameters:
    itembase_media_proxy.controller.class : Itembase\Bundle\MediaProxyBundle\Controller
    itembase_media_proxy.extension.class : Itembase\Bundle\MediaProxyBundle\Extension\MediaProxyExtension

services:
    itembase_media_proxy.controller:
        class: %itembase_media_proxy.controller.class%
        arguments: [%itembase_media_proxy.algorithm%, %itembase_media_proxy.secret%]

    itembase_media_proxy.extension:
        class: %itembase_media_proxy.extension.class%
        arguments: [%itembase_media_proxy.prefix_path%, %itembase_media_proxy.ignore_https%, %itembase_media_proxy.algorithm%, %itembase_media_proxy.secret%, @router]
        tags:
            -  { name: twig.extension }