parameters:
	ib_media_proxy.controller.class : Itembase\Bundle\MediaProxyBundle\Controller
	ib_media_proxy.extension.class : Itembase\Bundle\MediaProxyBundle\Extension\MediaProxyExtension

services:
	ib_media_proxy.controller:
        class: %ib_media_proxy.controller.class%
        arguments: [%ib_media_proxy.algorithm%, %ib_media_proxy.secret%]

    ib_media_proxy.extension:
        class: %ib_media_proxy.extension.class%
        arguments: [%ib_media_proxy.prefix_path%, %ib_media_proxy.ignore_https%, %ib_media_proxy.algorithm%, %ib_media_proxy.secret%, @router]
        tags:
            -  { name: twig.extension }